spring:
  cloud:
    gateway:
      routes:
        - id: medecin-service
          uri: lb://medecin-service
          predicates:
            - Path=/medecins/**
        - id: secretaire-service
          uri: lb://secretaire-service
          predicates:
            - Path=/secretaires/**
        - id: dossier-medical-service  # New route for the dossier medical service
          uri: lb://dossier-medical-service
          predicates:
            - Path=/dossiers/**  # Adjust the path according to your use case
          
    discovery:
      locator:
        enabled: true

server:
  port: 8888
